question 2

In [ ]:
import numpy as np
import scipy
import random
import scipy.stats as norm
import pandas as pd

In [ ]:
from numpy import nan

In [ ]:
mu=[ 2 , -2]
sigma = [[0.9 , 0.2],[0.2 , 0.3]]


In [ ]:
s1 = np.random.normal(2, 0.9 ,50)

In [ ]:
s2=np.random.normal(-2,0.3,50)

In [ ]:
s=np.array([s1,s2])

In [ ]:
s=s.T

In [ ]:
s.shape

(50, 2)

In [ ]:
s.mean(axis=0)

array([ 1.95956892, -2.06150967])

In [ ]:
np.cov(s.T)

array([[ 0.79461354, -0.01387712],
       [-0.01387712,  0.06436042]])

In [ ]:
s1 = np.random.normal(2, 0.9 ,5000)

In [ ]:
s2=np.random.normal(-2,0.3,5000)

In [ ]:
s=np.array([s1,s2])

In [ ]:
s=s.T

In [ ]:
s.shape

(5000, 2)

In [ ]:
s.mean(axis=0)

array([ 2.00635609, -2.00718201])

In [ ]:
np.cov(s.T)

array([[ 0.82188771, -0.00317376],
       [-0.00317376,  0.0889956 ]])

python question 1


In [ ]:
df1=pd.read_csv("data.csv")

In [ ]:
df1.head()

_type    _id     _score                                            _source
0   movies     97  20.848059  {'cast': ['Jeff Bridges', 'Bruce Boxleitner', ...
1   movies    507  10.478757  {'cast': ['Eric Stoltz', 'Julie Delpy', 'Jean-...
2   movies    811   9.831051  {'cast': ['Bruce Dern', 'Cliff Potts', 'Ron Ri...
3  tvshows  25222   9.288745  {'cast': ['Ron Rifkin', 'Eddie Barth', 'Charle...
4   movies    757   9.140831  {'cast': ['Margaret Rutherford', 'Ron Moody', ...

In [ ]:
df2=pd.read_csv("output.csv")

In [ ]:
df2.head()

_source
0  {'cast': ['Jeff Bridges', 'Bruce Boxleitner', ...
1  {'cast': ['Eric Stoltz', 'Julie Delpy', 'Jean-...
2  {'cast': ['Bruce Dern', 'Cliff Potts', 'Ron Ri...
3  {'cast': ['Ron Rifkin', 'Eddie Barth', 'Charle...
4  {'cast': ['Margaret Rutherford', 'Ron Moody', ...

In [ ]:
type(df2._source.loc[0])

str

In [ ]:
temp1=df1._source[0]

In [ ]:
temp2=df2.loc[0][0]

In [ ]:
temp1

"{'cast': ['Jeff Bridges', 'Bruce Boxleitner', 'David Warner', 'Cindy Morgan', 'Barnard Hughes', 'Dan Shor', 'Peter Jurasik', 'Tony Stephano', 'Craig Chudy', 'Vince Deadrick Jr.', 'Sam Schatz', 'Michael Dudikoff'], 'streaming_modes': ['Subscription'], 'thumbnail_id': {'mob': '97-mob-w342-zwSFEczP7AzqugAHHIX3zHniT0t', 'tv': '97-tv-w780-zwSFEczP7AzqugAHHIX3zHniT0t', 'web': '97-web-w500-zwSFEczP7AzqugAHHIX3zHniT0t'}, 'media_type': 'movies', 'year': '1982', 'genres': ['Science Fiction', 'Action', 'Adventure'], 'ratings': {'internet_movie_database': '6.8/10'}, 'language': 'English', 'id': '97', 'services': ['Jio Cinema'], 'title_name': 'Tron', 'sooper_original': False}"

In [ ]:
temp2

"{'cast': ['Jeff Bridges', 'Bruce Boxleitner', 'David Warner', 'Cindy Morgan', 'Barnard Hughes', 'Dan Shor', 'Peter Jurasik', 'Tony Stephano', 'Craig Chudy', 'Vince Deadrick Jr.', 'Sam Schatz', 'Michael Dudikoff'], 'streaming_modes': ['Subscription'], 'thumbnail_id': {'mob': '97-mob-w342-zwSFEczP7AzqugAHHIX3zHniT0t', 'tv': '97-tv-w780-zwSFEczP7AzqugAHHIX3zHniT0t', 'web': '97-web-w500-zwSFEczP7AzqugAHHIX3zHniT0t'}, 'media_type': 'movies', 'year': '1982', 'genres': ['Science Fiction', 'Action', 'Adventure'], 'ratings': {'internet_movie_database': '6.8/10'}, 'language': 'English', 'id': '97', 'services': ['Jio Cinema'], 'title_name': 'Tron', 'sooper_original': False, 'rating': nan, 'hide': nan, 'watchlist': nan, 'watched': nan}"

In [ ]:
df1["_source"]=df1['_source'].apply(eval)

In [ ]:
df1.head()

_type    _id     _score                                            _source
0   movies     97  20.848059  {'cast': ['Jeff Bridges', 'Bruce Boxleitner', ...
1   movies    507  10.478757  {'cast': ['Eric Stoltz', 'Julie Delpy', 'Jean-...
2   movies    811   9.831051  {'cast': ['Bruce Dern', 'Cliff Potts', 'Ron Ri...
3  tvshows  25222   9.288745  {'cast': ['Ron Rifkin', 'Eddie Barth', 'Charle...
4   movies    757   9.140831  {'cast': ['Margaret Rutherford', 'Ron Moody', ...

In [ ]:
for x in range(47):
  df2["_source"][x]=eval(df2['_source'][x])

In [ ]:
type(df1._source[0])

dict

In [ ]:
for x in range(47):
  df1["_source"][x]["rating"]=nan
  df1["_source"][x]["hide"]=nan
  df1["_source"][x]["watchlist"]=nan
  df1["_source"][x]["watched"]=nan


In [ ]:
df1["_source"][0],df2["_source"][1]

({'cast': ['Jeff Bridges',
   'Bruce Boxleitner',
   'David Warner',
   'Cindy Morgan',
   'Barnard Hughes',
   'Dan Shor',
   'Peter Jurasik',
   'Tony Stephano',
   'Craig Chudy',
   'Vince Deadrick Jr.',
   'Sam Schatz',
   'Michael Dudikoff'],
  'genres': ['Science Fiction', 'Action', 'Adventure'],
  'hide': nan,
  'id': '97',
  'language': 'English',
  'media_type': 'movies',
  'rating': nan,
  'ratings': {'internet_movie_database': '6.8/10'},
  'services': ['Jio Cinema'],
  'sooper_original': False,
  'streaming_modes': ['Subscription'],
  'thumbnail_id': {'mob': '97-mob-w342-zwSFEczP7AzqugAHHIX3zHniT0t',
   'tv': '97-tv-w780-zwSFEczP7AzqugAHHIX3zHniT0t',
   'web': '97-web-w500-zwSFEczP7AzqugAHHIX3zHniT0t'},
  'title_name': 'Tron',
  'watchlist': nan,
  'year': '1982'},
 {'cast': ['Eric Stoltz',
   'Julie Delpy',
   'Jean-Hugues Anglade',
   'Tai Thai',
   'Bruce Ramsay',
   'Kario Salem',
   'Salvator Xuereb',
   'Gary Kemp',
   'Martin Raymond',
   'Eric Pascal Chaltiel',
   'C

In [ ]:
df3=pd.read_csv("activity_data.csv")

In [ ]:
df3.head()

media_type  ...                                               hide
0  {'S': 'movies'}  ...  {'M': {'value': {'NULL': True}, 'timestamp': {...
1  {'S': 'movies'}  ...  {'M': {'value': {'NULL': True}, 'timestamp': {...
2  {'S': 'movies'}  ...  {'M': {'value': {'NULL': True}, 'timestamp': {...
3  {'S': 'movies'}  ...  {'M': {'value': {'NULL': True}, 'timestamp': {...
4  {'S': 'movies'}  ...  {'M': {'value': {'NULL': True}, 'timestamp': {...

[5 rows x 7 columns]

In [ ]:
for x in range(5):
  id=int(eval(df3["id"][x])["S"].split("_")[0])
  index=df1[df1["_id"]==id].index[0]
  if "NULL" in eval(df3["rating"][x])["M"]["value"]:
    df1["_source"][index]["rating"]=nan
  else:
    df1["_source"][index]["rating"]=int(eval(df3["rating"][x])["M"]["value"]["S"])

  if "NULL" in eval(df3["hide"][x])["M"]["value"]:
    df1["_source"][index]["hide"]=nan
  else:
    df1["_source"][index]["hide"]=int(eval(df3["hide"][x])["M"]["value"]["S"])


  if "NULL" in eval(df3["watched"][x])["M"]["value"]:
    df1["_source"][index]["watched"]=nan
  else:
    df1["_source"][index]["watched"]=int(eval(df3["watched"][x])["M"]["value"]["S"])


  if "NULL" in eval(df3["watchlist"][x])["M"]["value"]:
    df1["_source"][index]["watchlist"]=nan
  else:
    df1["_source"][index]["watchlist"]=int(eval(df3["watchlist"][x])["M"]["value"]["S"])



In [ ]:
df1[df1["_id"]==810]["_source"][9]

{'cast': ['Mike Myers',
  'Eddie Murphy',
  'Cameron Diaz',
  'Antonio Banderas',
  'Julie Andrews',
  'John Cleese',
  'Rupert Everett',
  'Eric Idle',
  'Justin Timberlake',
  'Susanne Blakeslee',
  'Cody Cameron',
  'Larry King',
  'Christopher Knights',
  'John Krasinski',
  'Ian McShane',
  'Cheri Oteri',
  'Regis Philbin',
  'Amy Poehler',
  'Seth Rogen',
  'Maya Rudolph',
  'Amy Sedaris',
  'Conrad Vernon',
  'Aron Warner',
  'Jasper Johannes Andrews',
  'Guillaume Aretos',
  'Kelly Asbury',
  'Zachary James Bernard',
  'Andrew Birch',
  'Sean Bishop',
  'Kelly Cooney',
  'Walt Dohrn',
  'Dante James Hauser',
  'Jordan Alexander Hauser',
  'Tom Kane',
  'Tom McGrath',
  'Chris Miller',
  'Latifa Ouaou',
  'Alina Phelan',
  'David P. Smith',
  'Mark Valley',
  'Kari Wahlgren',
  'Jamison Bright',
  'Krešimir Mikić',
  'Vedran Mlikota'],
 'genres': ['Fantasy', 'Adventure', 'Animation', 'Comedy', 'Family'],
 'hide': nan,
 'id': '810',
 'language': 'English',
 'media_type': 'movies'